version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: django-insecure-mlc$fzq7=m=&oh5$2de$vs*pw@mpzvbhbk90-*ya7oe+vsh4p+
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: matej
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: matej
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
