version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: matej
     POSTGRES_DB: mydb
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: "mydb"
    environment:
     POSTGRES_NAME: mydb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: matej
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
