apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: mvisuals
spec:
  template:
    spec:
      containers:
        - name: mvisuals-pod
          image: matt533/hw5_final:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations mvisuals && python manage.py migrate"]
          env:
              - name: DATABASE_USER
                value: postgres
              - name: DATABASE_NAME
                value: mydb
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: django-secrets
                    key: POSTGRES_PASSWORD
              - name: DATABASE_HOST
                value: mydb
              - name: DATABASE_PORT
                value: "5432"
      restartPolicy: Never
  backoffLimit: 5
