apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: mvisuals
  labels:
    app: mydb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/docker/volumes/hw5_final_pgdata/_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop