apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: mvisuals
  labels:
    app: mydb
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi